[package]
name = "chess993"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.6.0"
bytemuck = "1.19.0"
constmuck = { version = "1.1.0", features = ["derive"] }
strum = { version = "0.26.3", features = ["derive"] }
